# Generated by Django 4.2.17 on 2025-01-13 23:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('NIN', models.CharField(help_text='National Insurance Number', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('avg_price', models.DecimalField(decimal_places=2, help_text='Average price charged by the agent.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.BooleanField(default=True, help_text='Whether the agent is currently available for jobs.')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating based on customer reviews.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the agent.', null=True, upload_to='agent_profiles/')),
                ('bio', models.TextField(blank=True, help_text="Agent's professional biography and experience.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_worker_customer_review',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='services_re_worker__9cd71b_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='services_re_custome_7861f2_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='review',
            name='worker',
        ),
        migrations.AddField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent handling this booking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.agent'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'active'], name='services_ag_status_86ea00_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['rating'], name='services_ag_rating_5ce174_idx'),
        ),
    ]
