# Generated by Django 4.2.17 on 2025-01-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_agent_alter_review_options_and_more'),
        ('conversation', '0002_remove_conversationmessage_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='worker_conversations', to='services.worker'),
        ),
    ]
