# Generated by Django 4.2.17 on 2025-01-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversation', '0003_alter_conversation_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='read',
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_receiver_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='receiver_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_message_receiver_type', to='contenttypes.contenttype'),
        ),
    ]
